    msvc-iam:
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opticash-iam-db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: ruben123
            EUREKA_URI: http://eureka-server:8761/eureka
