server:
  port: 8081

spring:
  application:
    name: msvc-iam
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/opticash-iam-db
    username: postgres
    password: ruben123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

authorization:
  jwt:
    secret: "mysupersecretkeythatshouldbeatleast32chars"
    expiration:
      days: 7

documentation:
  application:
    description: "Microservicio de autenticación y autorización (IAM)"
    version: "1.0.0"