server:
  port: 8081

spring:
  application:
    name: msvc-iam
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: msvc-iam
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}

authorization:
  jwt:
    secret: "mysupersecretkeythatshouldbeatleast32chars"
    expiration:
      days: 7

documentation:
  application:
    description: "Microservicio de autenticación y autorización (IAM)"
    version: "1.0.0"
