server:
  port: 8081

spring:
  application:
    name: msvc-membercontributions

  datasource:
    url: jdbc:postgresql://localhost:5432/opticash_membercontributions_db
    username: postgres
    password: ruben123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # üö´ Desactiva eureka y config server
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration

# ‚öôÔ∏è Desactiva totalmente el cliente Eureka
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

authorization:
  jwt:
    secret: "mysupersecretkeythatshouldbeatleast32chars"
    expiration:
      days: 7

documentation:
  application:
    description: "Microservicio de contribuci√≥n de miembros"
    version: "1.0.0"
