server:
  port: 8081

spring:
  application:
    name: msvc-membercontributions

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/opticash_membercontributions_db
    username: postgres
    password: ruben123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  # ðŸš« Desactiva el cliente Eureka completamente
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration

authorization:
  jwt:
    secret: "mysupersecretkeythatshouldbeatleast32chars"
    expiration:
      days: 7

documentation:
  application:
    description: "Microservicio de contribuciÃ³n de miembros"
    version: "1.0.0"
