server:
  port: 8084

spring:
  application:
    name: msvc-contributions
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

services:
  households:
    url: lb://msvc-households
  bills:
    url: lb://msvc-bills
  iam:
    url: lb://msvc-iam

eureka:
  instance:
    hostname: msvc-contributions
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}

documentation:
  application:
    description: "Microservicio de Contributions"
    version: "1.0.0"
