server:
  port: 8084

spring:
  application:
    name: msvc-households
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/opticash-iam-db
    username: postgres
    password: ruben123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false

documentation:
  application:
    description: "Microservicio de Contributions"
    version: "1.0.0"